name: Node.js CD

on:
  push:
    branches: [main, dev]

  pull_request:
    branches: [main, dev]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: https://registry.npmjs.org

      - name: pnpm-setup
        uses: pnpm/action-setup@v2

      - name: "Installing dependencies"
        run: pnpm install

      - name: "Moving folder"
        run: pnpm run fockbuilder

      - name: "Initializing"
        run: |
          cd ./site-backend/apps/backend
          git init
          npm install
          git remote add pb https://github.com/Lazy-And-Focused/site.git
          git config --global user.name '${{ github.event.head_commit.author.name }}'
          git config --global user.email '${{ github.event.head_commit.author.username }}@${{ github.event.head_commit.author.email }}'
          git checkout -b site-backend
          git add .
          git fetch
          git commit -m "Publishing changes to backend"
          git push -f -u https://${{ secrets.PUSH_SECRET }}@github.com/Lazy-And-Focused/site.git site-backend
